export const NODES_REPOSITORY = Symbol("NODES_REPOSITORY");
export const EDGES_REPOSITORY = Symbol("EDGES_REPOSITORY");
export const GRAPH_TRAVERSAL_REPOSITORY = Symbol("GRAPH_TRAVERSAL_REPOSITORY");
export const TOOL_RUNS_REPOSITORY = Symbol("TOOL_RUNS_REPOSITORY");
export const EVIDENCE_FILES_REPOSITORY = Symbol("EVIDENCE_FILES_REPOSITORY");
export const NOTES_REPOSITORY = Symbol("NOTES_REPOSITORY");
export const REPORTS_REPOSITORY = Symbol("REPORTS_REPOSITORY");
